### ISSUE TITLE
Transfer to enzymejs org

### ISSUE THREAD

**Issue by ljharb** [enzymejs/react-shallow-renderer#16]
You've been invited to the repo; could we transfer the repo to the new enzyme org?

**Comment by NMinhNguyen** [comment]
@ljharb thanks for the invite. Would you be able to present the benefits of associating it with the Enzyme org given this package itself has no dependency on Enzyme?

**Comment by ljharb** [comment]
What depends on the shallow renderer besides enzyme? I’m under the impression that enzyme is the primary, and possibly only, consumer of it - enough that there’s been discussions with the react team about pulling it into enzyme for years.

**Comment by it11ah1** [comment]
Can someone try to explain why it is so important whether the code is in this or in a other repo to just fix important problems?
Placed in the react-test-renderer package as part of react the useEffect hook was introduced with noOp on January of 2019. And the same noOp code now lives in the react-shallow-renderer repo.

So, avoid the millions of useless mounts in tests out there flooding the DOMs just to cover effects/hooks... regardless of the concrete repo/owner... please...

**Comment by ljharb** [comment]
@it11ah1 that sounds like a different issue, entirely unrelated to this one - perhaps file a new issue?

**Comment by thedanchez** [comment]
Any updates/movement on this? It would be great to get the ball rolling so improvements can start..

**Comment by mwallace72** [comment]
@NMinhNguyen @ljharb is there movement on resolving this? I understand it is partially blocking https://github.com/enzymejs/enzyme/issues/2011

**Comment by NMinhNguyen** [comment]
Sorry, been a little busy. Thanks for the reminder @mwallace72, I'll begin transferring to the Enzyme org soon, however it shouldn't really matter what org a package belongs to, there's nothing stopping a PR being opened against this repo.

**Comment by ljharb** [comment]
Proper admin privileges and CI configuration and whatnot require it to be in an org; also in general, i prefer enzyme or the react team to own as many of enzyme's dependencies as possible.

**Comment by rodoabad** [comment]
@ljharb @NMinhNguyen what's the update on this?

**Comment by thedanchez** [comment]
@NMinhNguyen can you please transfer the repository ownership over to @ljharb and the Enzyme organization?

**Comment by NMinhNguyen** [comment]
I wouldn't mind transferring but I'm afraid I don't have the capacity to do the following:

> Proper admin privileges and CI configuration and whatnot require it to be in an org

**Comment by ljharb** [comment]
@NMinhNguyen what that means is that once it's transferred, as an org admin i'll be able to fully administer the repo (as will you, as a repo admin). As your personal repo, you're the only person that can administer it.

As a personal admin, you can transfer it to the org on the "options" page in settings.

**Comment by NMinhNguyen** [comment]
> @NMinhNguyen what that means is that once it's transferred, as an org admin i'll be able to fully administer the repo (as will you, as a repo admin). As your personal repo, you're the only person that can administer it.
> 
> As a personal admin, you can transfer it to the org on the "options" page in settings.

Right, completely misinterpreted that! I thought that the codebase had to be in a certain shape before it was eligible to be transferred. I’ve transferred it now, so will go ahead and close this issue.

**Comment by NMinhNguyen** [comment]
@ljharb could you invite the React core team members too? They had admin access to this repo when it was still my personal one.

**Comment by ljharb** [comment]
The permissions have not changed, so anyone who had access still does.

**Comment by ljharb** [comment]
Thank you! I'll add the task to my list for updating various things with the project.
