### ISSUE TITLE
How to use second argument of render function context?

### ISSUE THREAD

**Issue by code-guru** [enzymejs/react-shallow-renderer#99]
What is use case for the second argument of render function `context`, is it possible to pass redux context using the the argument? 

Is there any documentation of example how to use the context argument?
Thanks :-)

**Comment by ljharb** [comment]
It’s used to pass “legacy” context - so, it depends on which version of redux you’re talking about,

**Comment by code-guru** [comment]
I'm using the latest react/redux. Thanks for clarification, is this project from the official react-team? Since it is mentioned in the react documentation? If so may I ask  why it is not hosted in the react repo like other related projects?

**Comment by ljharb** [comment]
The react team no longer maintains it.
